import Foundation

/// Parsed representation of an `ios-command-fixture.json` capture artifact.
///
/// The fixture is generated by `tools/capture/export_run_pack.sh` and can also be
/// hand-curated under `docs/captures/curated/` for deterministic replay tests.
struct RunPackReplayFixture: Decodable {
    let exchanges: [Exchange]

    struct Exchange: Decodable {
        let observationID: String?
        let observedAt: String?
        let signalKey: String?
        let sourceSignal: String?
        let status: String?
        let rawPayloadRef: String?
        let command: String?
        let response: String?

        private enum CodingKeys: String, CodingKey {
            case observationID = "observation_id"
            case observedAt = "observed_at"
            case signalKey = "signal_key"
            case sourceSignal = "source_signal"
            case status
            case rawPayloadRef = "raw_payload_ref"
            case command
            case response
        }
    }
}

/// One replay step consumed by `ReplayOBDTransport`.
struct ReplayCommandStep: Equatable {
    enum Outcome: Equatable {
        case response(String)
        case transportError(String)
        case timeout(String)
    }

    let command: String
    let outcome: Outcome
}

enum RunPackReplayFixtureError: Error, LocalizedError, Equatable {
    case fixtureFileNotFound(URL)
    case emptyExchanges
    case malformedExchange(message: String)
    case startCommandNotFound(command: String, occurrence: Int)
    case repositoryRootNotFound(startingAt: URL)

    var errorDescription: String? {
        switch self {
        case let .fixtureFileNotFound(url):
            return "Fixture file not found: \(url.path)"
        case .emptyExchanges:
            return "Fixture contains no exchanges."
        case let .malformedExchange(message):
            return "Fixture exchange is malformed: \(message)"
        case let .startCommandNotFound(command, occurrence):
            return "Could not find command \(command) occurrence \(occurrence) in fixture."
        case let .repositoryRootNotFound(startingAt):
            return "Could not locate repository root while walking from \(startingAt.path)."
        }
    }
}

extension RunPackReplayFixture {
    static func load(from url: URL) throws -> RunPackReplayFixture {
        guard FileManager.default.fileExists(atPath: url.path) else {
            throw RunPackReplayFixtureError.fixtureFileNotFound(url)
        }
        let data = try Data(contentsOf: url)
        let decoded = try JSONDecoder().decode(RunPackReplayFixture.self, from: data)
        guard !decoded.exchanges.isEmpty else {
            throw RunPackReplayFixtureError.emptyExchanges
        }
        return decoded
    }

    static func loadCuratedFixture(
        named fixtureName: String,
        relativeToFilePath filePath: String = #filePath
    ) throws -> RunPackReplayFixture {
        let startURL = URL(fileURLWithPath: filePath).deletingLastPathComponent()
        let repositoryRoot = try locateRepositoryRoot(startingAt: startURL)
        let fixtureURL = repositoryRoot
            .appendingPathComponent("docs", isDirectory: true)
            .appendingPathComponent("captures", isDirectory: true)
            .appendingPathComponent("curated", isDirectory: true)
            .appendingPathComponent(fixtureName, isDirectory: true)
            .appendingPathComponent("ios-command-fixture.json", isDirectory: false)
        return try load(from: fixtureURL)
    }

    func replaySteps() throws -> [ReplayCommandStep] {
        try replaySteps(startingAt: nil, occurrence: 1)
    }

    func replaySteps(
        startingAt command: String?,
        occurrence: Int = 1
    ) throws -> [ReplayCommandStep] {
        let allSteps = try exchanges.enumerated().map { index, exchange in
            try buildReplayStep(exchange: exchange, exchangeIndex: index)
        }

        guard let command else {
            return allSteps
        }

        guard occurrence > 0 else {
            throw RunPackReplayFixtureError.startCommandNotFound(command: command, occurrence: occurrence)
        }

        var matchesSeen = 0
        for index in allSteps.indices where allSteps[index].command.caseInsensitiveCompare(command) == .orderedSame {
            matchesSeen += 1
            if matchesSeen == occurrence {
                return Array(allSteps[index...])
            }
        }

        throw RunPackReplayFixtureError.startCommandNotFound(command: command, occurrence: occurrence)
    }

    private static func locateRepositoryRoot(startingAt initialURL: URL) throws -> URL {
        var currentURL = initialURL
        while true {
            let gitDirectory = currentURL.appendingPathComponent(".git", isDirectory: true)
            if FileManager.default.fileExists(atPath: gitDirectory.path) {
                return currentURL
            }

            let parentURL = currentURL.deletingLastPathComponent()
            if parentURL.path == currentURL.path {
                break
            }
            currentURL = parentURL
        }

        throw RunPackReplayFixtureError.repositoryRootNotFound(startingAt: initialURL)
    }

    private func buildReplayStep(
        exchange: Exchange,
        exchangeIndex: Int
    ) throws -> ReplayCommandStep {
        let command = normalizedCommand(from: exchange)
        guard let command, !command.isEmpty else {
            throw RunPackReplayFixtureError.malformedExchange(
                message: "missing command at exchange index \(exchangeIndex)"
            )
        }

        let status = (exchange.status ?? "ok").lowercased()
        if status == "error" {
            let errorMessage = parseErrorMessage(from: exchange.rawPayloadRef)
                ?? "replay transport error for command \(command)"
            if errorMessage.range(of: "timeout", options: [.caseInsensitive]) != nil {
                return ReplayCommandStep(command: command, outcome: .timeout(errorMessage))
            }
            return ReplayCommandStep(command: command, outcome: .transportError(errorMessage))
        }

        let response = normalizedResponse(from: exchange)
        guard let response else {
            throw RunPackReplayFixtureError.malformedExchange(
                message: "missing response for command \(command) at exchange index \(exchangeIndex)"
            )
        }

        return ReplayCommandStep(command: command, outcome: .response(response))
    }

    private func normalizedCommand(from exchange: Exchange) -> String? {
        if let command = exchange.command?.trimmingCharacters(in: .whitespacesAndNewlines),
           !command.isEmpty
        {
            return command
        }

        guard let rawPayloadRef = exchange.rawPayloadRef else {
            return nil
        }
        return parseField(rawPayloadRef, fieldName: "cmd")
    }

    private func normalizedResponse(from exchange: Exchange) -> String? {
        if let response = exchange.response?.trimmingCharacters(in: .whitespacesAndNewlines),
           !response.isEmpty
        {
            return response
        }

        guard let rawPayloadRef = exchange.rawPayloadRef else {
            return nil
        }

        return parseField(rawPayloadRef, fieldName: "resp")
    }

    private func parseErrorMessage(from rawPayloadRef: String?) -> String? {
        guard let rawPayloadRef else {
            return nil
        }

        guard let markerRange = rawPayloadRef.range(of: "error=") else {
            return nil
        }

        let suffix = rawPayloadRef[markerRange.upperBound...]
            .trimmingCharacters(in: .whitespacesAndNewlines)
        guard !suffix.isEmpty else {
            return nil
        }
        return suffix
    }

    private func parseField(_ text: String, fieldName: String) -> String? {
        let marker = "\(fieldName)="
        guard let markerRange = text.range(of: marker) else {
            return nil
        }

        let suffix = text[markerRange.upperBound...]
        let fieldValue = suffix.prefix { character in
            !(character == "|" || character == "\n" || character == "\r")
        }
        let trimmed = fieldValue.trimmingCharacters(in: .whitespacesAndNewlines)
        return trimmed.isEmpty ? nil : trimmed
    }
}
