import Foundation

/// Parsed representation of replay artifacts used in OBD offline tests.
///
/// Supported source formats:
/// - `ios-command-fixture.json` generated by `tools/capture/export_run_pack.sh`
/// - iOS-exported run-pack JSON files containing `command_exchanges`
///
/// Artifacts can be hand-curated under `docs/captures/curated/`.
struct RunPackReplayFixture: Decodable {
    let exchanges: [Exchange]

    private struct DynamicCodingKey: CodingKey {
        let stringValue: String
        let intValue: Int?

        init?(stringValue: String) {
            self.stringValue = stringValue
            intValue = nil
        }

        init?(intValue: Int) {
            return nil
        }
    }

    struct Exchange: Decodable {
        let observationID: String?
        let observedAt: String?
        let signalKey: String?
        let sourceSignal: String?
        let status: String?
        let rawPayloadRef: String?
        let command: String?
        let response: String?

        private enum CodingKeys: String, CodingKey {
            case observationID = "observation_id"
            case observedAt = "observed_at"
            case signalKey = "signal_key"
            case sourceSignal = "source_signal"
            case status
            case rawPayloadRef = "raw_payload_ref"
            case command
            case response
        }
    }

    private struct RunPackCommandExchange: Decodable {
        let id: String?
        let startedAt: String?
        let command: String?
        let rawResponse: String?
        let parseOutcome: String?

        private enum CodingKeys: String, CodingKey {
            case id
            case startedAt = "started_at"
            case command
            case rawResponse = "raw_response"
            case parseOutcome = "parse_outcome"
        }
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: DynamicCodingKey.self)

        if let exchangesKey = DynamicCodingKey(stringValue: "exchanges"),
           container.contains(exchangesKey)
        {
            exchanges = try container.decode([Exchange].self, forKey: exchangesKey)
            return
        }

        if let commandExchangesKey = DynamicCodingKey(stringValue: "command_exchanges"),
           container.contains(commandExchangesKey)
        {
            let commandExchanges = try container.decode([RunPackCommandExchange].self, forKey: commandExchangesKey)
            exchanges = commandExchanges.map { commandExchange in
                let normalizedOutcome = (commandExchange.parseOutcome ?? "ok").lowercased()
                let status: String
                switch normalizedOutcome {
                case "ok":
                    status = "ok"
                case "unavailable", "not_supported":
                    status = "unavailable"
                case "error", "timeout":
                    status = "error"
                default:
                    status = normalizedOutcome
                }

                let rawPayloadRef: String?
                if status == "error",
                   let rawResponse = commandExchange.rawResponse,
                   !rawResponse.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
                {
                    rawPayloadRef = "error=\(rawResponse)"
                } else {
                    rawPayloadRef = nil
                }

                return Exchange(
                    observationID: commandExchange.id,
                    observedAt: commandExchange.startedAt,
                    signalKey: nil,
                    sourceSignal: nil,
                    status: status,
                    rawPayloadRef: rawPayloadRef,
                    command: commandExchange.command,
                    response: commandExchange.rawResponse
                )
            }
            return
        }

        throw DecodingError.dataCorrupted(
            .init(
                codingPath: decoder.codingPath,
                debugDescription: "Unsupported replay fixture format. Expected `exchanges` or `command_exchanges`."
            )
        )
    }
}

/// One replay step consumed by `ReplayOBDTransport`.
struct ReplayCommandStep: Equatable {
    enum Outcome: Equatable {
        case response(String)
        case transportError(String)
        case timeout(String)
    }

    let command: String
    let outcome: Outcome
}

enum RunPackReplayFixtureError: Error, LocalizedError, Equatable {
    case fixtureFileNotFound(URL)
    case emptyExchanges
    case malformedExchange(message: String)
    case startCommandNotFound(command: String, occurrence: Int)
    case repositoryRootNotFound(startingAt: URL)

    var errorDescription: String? {
        switch self {
        case let .fixtureFileNotFound(url):
            return "Fixture file not found: \(url.path)"
        case .emptyExchanges:
            return "Fixture contains no exchanges."
        case let .malformedExchange(message):
            return "Fixture exchange is malformed: \(message)"
        case let .startCommandNotFound(command, occurrence):
            return "Could not find command \(command) occurrence \(occurrence) in fixture."
        case let .repositoryRootNotFound(startingAt):
            return "Could not locate repository root while walking from \(startingAt.path)."
        }
    }
}

extension RunPackReplayFixture {
    static func load(from url: URL) throws -> RunPackReplayFixture {
        guard FileManager.default.fileExists(atPath: url.path) else {
            throw RunPackReplayFixtureError.fixtureFileNotFound(url)
        }
        let data = try Data(contentsOf: url)
        let decoded = try JSONDecoder().decode(RunPackReplayFixture.self, from: data)
        guard !decoded.exchanges.isEmpty else {
            throw RunPackReplayFixtureError.emptyExchanges
        }
        return decoded
    }

    static func loadCuratedFixture(
        named fixtureName: String,
        fileName: String = "ios-command-fixture.json",
        relativeToFilePath filePath: String = #filePath
    ) throws -> RunPackReplayFixture {
        let startURL = URL(fileURLWithPath: filePath).deletingLastPathComponent()
        let repositoryRoot = try locateRepositoryRoot(startingAt: startURL)
        let fixtureURL = repositoryRoot
            .appendingPathComponent("docs", isDirectory: true)
            .appendingPathComponent("captures", isDirectory: true)
            .appendingPathComponent("curated", isDirectory: true)
            .appendingPathComponent(fixtureName, isDirectory: true)
            .appendingPathComponent(fileName, isDirectory: false)
        return try load(from: fixtureURL)
    }

    func replaySteps() throws -> [ReplayCommandStep] {
        try replaySteps(startingAt: nil, occurrence: 1)
    }

    func replaySteps(
        startingAt command: String?,
        occurrence: Int = 1
    ) throws -> [ReplayCommandStep] {
        let allSteps = try exchanges.enumerated().map { index, exchange in
            try buildReplayStep(exchange: exchange, exchangeIndex: index)
        }

        guard let command else {
            return allSteps
        }

        guard occurrence > 0 else {
            throw RunPackReplayFixtureError.startCommandNotFound(command: command, occurrence: occurrence)
        }

        var matchesSeen = 0
        for index in allSteps.indices where allSteps[index].command.caseInsensitiveCompare(command) == .orderedSame {
            matchesSeen += 1
            if matchesSeen == occurrence {
                return Array(allSteps[index...])
            }
        }

        throw RunPackReplayFixtureError.startCommandNotFound(command: command, occurrence: occurrence)
    }

    private static func locateRepositoryRoot(startingAt initialURL: URL) throws -> URL {
        var currentURL = initialURL
        while true {
            let gitDirectory = currentURL.appendingPathComponent(".git", isDirectory: true)
            if FileManager.default.fileExists(atPath: gitDirectory.path) {
                return currentURL
            }

            let parentURL = currentURL.deletingLastPathComponent()
            if parentURL.path == currentURL.path {
                break
            }
            currentURL = parentURL
        }

        throw RunPackReplayFixtureError.repositoryRootNotFound(startingAt: initialURL)
    }

    private func buildReplayStep(
        exchange: Exchange,
        exchangeIndex: Int
    ) throws -> ReplayCommandStep {
        let command = normalizedCommand(from: exchange)
        guard let command, !command.isEmpty else {
            throw RunPackReplayFixtureError.malformedExchange(
                message: "missing command at exchange index \(exchangeIndex)"
            )
        }

        let status = (exchange.status ?? "ok").lowercased()
        if status == "error" {
            let errorMessage = parseErrorMessage(from: exchange.rawPayloadRef)
                ?? "replay transport error for command \(command)"
            if errorMessage.range(of: "timeout", options: [.caseInsensitive]) != nil {
                return ReplayCommandStep(command: command, outcome: .timeout(errorMessage))
            }
            return ReplayCommandStep(command: command, outcome: .transportError(errorMessage))
        }

        let response = normalizedResponse(from: exchange)
        guard let response else {
            throw RunPackReplayFixtureError.malformedExchange(
                message: "missing response for command \(command) at exchange index \(exchangeIndex)"
            )
        }

        return ReplayCommandStep(command: command, outcome: .response(response))
    }

    private func normalizedCommand(from exchange: Exchange) -> String? {
        if let command = exchange.command?.trimmingCharacters(in: .whitespacesAndNewlines),
           !command.isEmpty
        {
            return command
        }

        guard let rawPayloadRef = exchange.rawPayloadRef else {
            return nil
        }
        return parseField(rawPayloadRef, fieldName: "cmd")
    }

    private func normalizedResponse(from exchange: Exchange) -> String? {
        if let response = exchange.response?.trimmingCharacters(in: .whitespacesAndNewlines),
           !response.isEmpty
        {
            return response
        }

        guard let rawPayloadRef = exchange.rawPayloadRef else {
            return nil
        }

        return parseField(rawPayloadRef, fieldName: "resp")
    }

    private func parseErrorMessage(from rawPayloadRef: String?) -> String? {
        guard let rawPayloadRef else {
            return nil
        }

        guard let markerRange = rawPayloadRef.range(of: "error=") else {
            return nil
        }

        let suffix = rawPayloadRef[markerRange.upperBound...]
            .trimmingCharacters(in: .whitespacesAndNewlines)
        guard !suffix.isEmpty else {
            return nil
        }
        return suffix
    }

    private func parseField(_ text: String, fieldName: String) -> String? {
        let marker = "\(fieldName)="
        guard let markerRange = text.range(of: marker) else {
            return nil
        }

        let suffix = text[markerRange.upperBound...]
        let fieldValue = suffix.prefix { character in
            !(character == "|" || character == "\n" || character == "\r")
        }
        let trimmed = fieldValue.trimmingCharacters(in: .whitespacesAndNewlines)
        return trimmed.isEmpty ? nil : trimmed
    }
}
