use super::LockedKpiSpec;

/// Static KPI catalog used for provenance logging and contract validation.
pub(crate) const LOCKED_KPI_SPECS: &[LockedKpiSpec] = &[
    LockedKpiSpec {
        ranking_type: "ev_range_efficiency",
        kpi_key: "ev_net_energy_efficiency",
        formula: "median(((delta_soc_pct/100) * DEFAULT_USABLE_BATTERY_KWH * 1000) / delta_km)",
        required_signals: &["distance.odometer", "ev.soc_pct"],
        optional_signals: &["power.battery_power_kw", "environment.ambient_temp_c"],
    },
    LockedKpiSpec {
        ranking_type: "ev_range_efficiency",
        kpi_key: "ev_estimated_practical_range",
        formula: "latest_soc_pct * median(delta_km / delta_soc_pct)",
        required_signals: &["distance.odometer", "ev.soc_pct"],
        optional_signals: &["environment.ambient_temp_c"],
    },
    LockedKpiSpec {
        ranking_type: "ev_range_efficiency",
        kpi_key: "ev_urban_efficiency",
        formula: "median(ev_net_energy_efficiency for segments where speed.vehicle < 45 km/h)",
        required_signals: &["distance.odometer", "ev.soc_pct", "speed.vehicle"],
        optional_signals: &[],
    },
    LockedKpiSpec {
        ranking_type: "ev_range_efficiency",
        kpi_key: "ev_highway_efficiency",
        formula: "median(ev_net_energy_efficiency for segments where speed.vehicle >= 80 km/h)",
        required_signals: &["distance.odometer", "ev.soc_pct", "speed.vehicle"],
        optional_signals: &[],
    },
    LockedKpiSpec {
        ranking_type: "ev_range_efficiency",
        kpi_key: "regeneration_recovery_ratio",
        formula: "100 * regen_energy_wh / (regen_energy_wh + traction_energy_wh) over integrated power windows",
        required_signals: &["ev.regen_power_kw", "ev.traction_power_kw"],
        optional_signals: &[],
    },
    LockedKpiSpec {
        ranking_type: "ev_range_efficiency",
        kpi_key: "soc_depletion_rate_per_100km",
        formula: "100 / median(delta_km / delta_soc_pct)",
        required_signals: &["distance.odometer", "ev.soc_pct"],
        optional_signals: &[],
    },
    LockedKpiSpec {
        ranking_type: "ev_range_efficiency",
        kpi_key: "ev_range_efficiency_score",
        formula: "0.65 * normalized_efficiency_component + 0.35 * normalized_estimated_range_component",
        required_signals: &["distance.odometer", "ev.soc_pct"],
        optional_signals: &["speed.vehicle", "environment.ambient_temp_c"],
    },
    LockedKpiSpec {
        ranking_type: "ev_charging_performance",
        kpi_key: "temp_adjusted_charge_acceptance_score",
        formula: "clamp(100 * median(all_charge_kw) / median(mild_charge_kw), 0, 120)",
        required_signals: &["ev.charging_state", "ev.charge_power_kw", "ev.soc_pct"],
        optional_signals: &[
            "ev.battery_temp_c",
            "environment.ambient_temp_c",
            "ev.charger_type",
        ],
    },
    LockedKpiSpec {
        ranking_type: "ev_charging_performance",
        kpi_key: "cold_weather_charge_speed_retention",
        formula: "100 * median(cold_charge_kw) / median(mild_charge_kw)",
        required_signals: &["ev.charging_state", "ev.charge_power_kw", "ev.soc_pct"],
        optional_signals: &[
            "ev.battery_temp_c",
            "environment.ambient_temp_c",
            "ev.charger_type",
        ],
    },
    LockedKpiSpec {
        ranking_type: "ev_charging_performance",
        kpi_key: "charging_performance_score",
        formula: "0.6 * temp_adjusted_charge_acceptance_score + 0.4 * cold_weather_charge_speed_retention",
        required_signals: &["ev.charging_state", "ev.charge_power_kw", "ev.soc_pct"],
        optional_signals: &["ev.battery_temp_c", "environment.ambient_temp_c"],
    },
    LockedKpiSpec {
        ranking_type: "ev_temperature_impact",
        kpi_key: "cold_weather_range_retention",
        formula: "100 * median(cold_km_per_soc) / median(mild_km_per_soc)",
        required_signals: &[
            "distance.odometer",
            "ev.soc_pct",
            "environment.ambient_temp_c",
        ],
        optional_signals: &["ev.battery_temp_c"],
    },
    LockedKpiSpec {
        ranking_type: "ev_temperature_impact",
        kpi_key: "range_temperature_sensitivity_index",
        formula: "max(0, -slope(km_per_soc vs temp_c) * 10 / mild_km_per_soc * 100)",
        required_signals: &[
            "distance.odometer",
            "ev.soc_pct",
            "environment.ambient_temp_c",
        ],
        optional_signals: &["ev.battery_temp_c"],
    },
    LockedKpiSpec {
        ranking_type: "ev_temperature_impact",
        kpi_key: "cold_weather_charge_speed_retention",
        formula: "100 * median(cold_charge_kw) / median(mild_charge_kw)",
        required_signals: &["ev.charging_state", "ev.charge_power_kw", "ev.soc_pct"],
        optional_signals: &["ev.battery_temp_c", "environment.ambient_temp_c"],
    },
    LockedKpiSpec {
        ranking_type: "ev_composite",
        kpi_key: "ev_composite_base_score",
        formula: "0.6 * ev_range_efficiency_score + 0.4 * charging_performance_score",
        required_signals: &[],
        optional_signals: &[],
    },
    LockedKpiSpec {
        ranking_type: "ev_composite",
        kpi_key: "ev_health_modifier_penalty",
        formula: "min(10, (MIL_ON ? 6 : 0) + min(4, 0.5 * distinct_active_dtc_count))",
        required_signals: &["diag.mil_on", "diag.dtcs_active"],
        optional_signals: &[],
    },
    LockedKpiSpec {
        ranking_type: "ev_composite",
        kpi_key: "ev_composite_score",
        formula: "clamp(ev_composite_base_score - ev_health_modifier_penalty, 0, 100)",
        required_signals: &[],
        optional_signals: &[],
    },
];
